name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      -
jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Builds and Starts
        run: |
          docker-compose up -d

      - name: Run Integration Tests
        run: |
          docker-compose up -d
          docker exec realworld_drash deno test -A --unstable tests/integration/test.ts

      - name: Run Unit Tests
        run: |
          docker-compose up -d
          docker exec realworld_drash deno test -A --unstable tests/unit/models/base_model_test.ts

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest --alluredir=allure-results

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

  linter:
      # Only one OS is required since fmt is cross platform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Formatter
        run: deno fmt --check --unstable --ignore='src/public,src/vue,src/package.json,src/webpack.config.js'

      - name: Linter
        run: deno lint --unstable --ignore='src/public,src/vue,src/package.json,src/webpack.config.js'